"""
sample_data/seed_mongodb.py
Seed MongoDB Atlas directly from the sample Excel files.

Usage (from project root):
    venv\Scripts\python.exe -m sample_data.seed_mongodb

Or (from backend/ directory):
    python -m sample_data.seed_mongodb

Requires:
    - MONGO_URI set in .env (or environment)
    - Sample .xlsx files generated by generate_sample_data.py
"""

import os
import sys
from pathlib import Path
from datetime import datetime, timezone

# Ensure backend/ is on sys.path so imports work
BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Load .env before any app imports
from dotenv import load_dotenv
env_path = BACKEND_DIR.parent / ".env"
if env_path.exists():
    load_dotenv(env_path)
    print(f"  Loaded .env from {env_path}")

import pandas as pd
import numpy as np
from pymongo import MongoClient

SAMPLE_DIR = Path(__file__).resolve().parent
MONGO_URI = os.getenv("MONGO_URI", "")
DB_NAME = os.getenv("MONGO_DB_NAME", "campus_ai")


def get_db():
    """Connect to MongoDB and return the database object."""
    if not MONGO_URI:
        print("ERROR: MONGO_URI is not set. Set it in .env or environment variables.")
        sys.exit(1)
    client = MongoClient(MONGO_URI)
    return client[DB_NAME]


def seed_students(db):
    path = SAMPLE_DIR / "students.xlsx"
    if not path.exists():
        print("  SKIP students.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    now = datetime.now(timezone.utc)
    count = 0
    for _, row in df.iterrows():
        s_id = str(row.get("student_id", "")).strip()
        if not s_id:
            continue
        doc = {
            "student_id": s_id,
            "name": str(row.get("name", "")),
            "email": str(row.get("email", "")),
            "phone": str(row.get("phone", "")),
            "department": str(row.get("department", "General")),
            "batch_year": int(row.get("batch_year", 2026)),
            "semester": int(row.get("semester", 1)),
            "section": str(row.get("section", "A")),
            "cgpa": float(row.get("cgpa", 0.0)),
            "is_hostel": False,
            "updated_at": now,
        }
        db.students.update_one(
            {"student_id": s_id},
            {"$set": doc, "$setOnInsert": {"created_at": now}},
            upsert=True,
        )
        count += 1
    print(f"  [OK] Seeded {count} students")


def seed_faculty(db):
    path = SAMPLE_DIR / "faculty.xlsx"
    if not path.exists():
        print("  SKIP faculty.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    now = datetime.now(timezone.utc)
    count = 0
    for _, row in df.iterrows():
        f_id = str(row.get("faculty_id", "")).strip()
        if not f_id:
            continue
        subjects = str(row.get("subjects", ""))
        doc = {
            "faculty_id": f_id,
            "name": str(row.get("name", "")),
            "email": str(row.get("email", "")),
            "department": str(row.get("department", "General")),
            "designation": str(row.get("designation", "Lecturer")),
            "qualification": str(row.get("qualification", "PhD")),
            "experience_years": int(row.get("experience_years", 0)),
            "subjects": [s.strip() for s in subjects.split(",")] if subjects else [],
            "updated_at": now,
        }
        db.faculty.update_one(
            {"faculty_id": f_id},
            {"$set": doc, "$setOnInsert": {"created_at": now}},
            upsert=True,
        )
        count += 1
    print(f"  [OK] Seeded {count} faculty members")


def seed_attendance(db):
    path = SAMPLE_DIR / "attendance.xlsx"
    if not path.exists():
        print("  SKIP attendance.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    db.attendance.delete_many({})
    now = datetime.now(timezone.utc)
    records = []
    for _, row in df.iterrows():
        s_id = str(row.get("student_id", "")).strip()
        if not s_id:
            continue
        status_raw = str(row.get("status", "absent")).strip().lower()
        normalized = "present" if status_raw in {"present", "p", "1", "yes", "true"} else "absent"
        raw_date = row.get("date")
        if isinstance(raw_date, str):
            try:
                date_obj = pd.to_datetime(raw_date).to_pydatetime()
            except Exception:
                date_obj = now
        elif hasattr(raw_date, "to_pydatetime"):
            date_obj = raw_date.to_pydatetime()
        else:
            date_obj = now
        # Ensure timezone-aware
        if date_obj.tzinfo is None:
            date_obj = date_obj.replace(tzinfo=timezone.utc)

        records.append({
            "student_id": s_id,
            "date": date_obj,
            "status": normalized,
            "course": str(row.get("course", "")),
            "department": str(row.get("department", "")),
        })
    if records:
        db.attendance.insert_many(records)
    print(f"  [OK] Seeded {len(records)} attendance records")


def seed_placements(db):
    path = SAMPLE_DIR / "placements.xlsx"
    if not path.exists():
        print("  SKIP placements.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    db.placements.delete_many({})
    records = []
    for _, row in df.iterrows():
        s_id = str(row.get("student_id", "")).strip()
        if not s_id:
            continue
        records.append({
            "student_id": s_id,
            "name": str(row.get("name", "")),
            "company_name": str(row.get("company_name", "")),
            "package_lpa": float(row.get("package_lpa", 0)),
            "status": str(row.get("status", "unplaced")).strip().lower(),
            "year": int(row.get("year", 2026)),
            "department": str(row.get("department", "")),
        })
    if records:
        db.placements.insert_many(records)
    print(f"  [OK] Seeded {len(records)} placement records")


def seed_results(db):
    path = SAMPLE_DIR / "results.xlsx"
    if not path.exists():
        print("  SKIP results.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    db.results.delete_many({})
    records = []
    for _, row in df.iterrows():
        s_id = str(row.get("student_id", "")).strip()
        if not s_id:
            continue
        records.append({
            "student_id": s_id,
            "subject": str(row.get("subject", "")),
            "marks": float(row.get("marks", 0)),
            "cgpa": float(row.get("cgpa", 0)),
            "semester": int(row.get("semester", 1)),
        })
    if records:
        db.results.insert_many(records)
    print(f"  [OK] Seeded {len(records)} results")


def seed_timetable(db):
    path = SAMPLE_DIR / "timetable.xlsx"
    if not path.exists():
        print("  SKIP timetable.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    db.timetable.delete_many({})
    records = []
    for _, row in df.iterrows():
        records.append({
            "day": str(row.get("day", "")),
            "period": str(row.get("period", "")),
            "subject": str(row.get("subject", "")),
            "time": str(row.get("time", "")),
            "slot": str(row.get("slot", "")),
            "department": str(row.get("department", "")),
            "faculty_name": str(row.get("faculty", "")),
        })
    if records:
        db.timetable.insert_many(records)
    print(f"  [OK] Seeded {len(records)} timetable slots")


def seed_library(db):
    path = SAMPLE_DIR / "library.xlsx"
    if not path.exists():
        print("  SKIP library.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    db.library.delete_many({})
    records = []
    for _, row in df.iterrows():
        records.append({
            "title": str(row.get("title", "")),
            "author": str(row.get("author", "")),
            "isbn": str(row.get("isbn", "")),
            "category": str(row.get("category", "")),
            "available": int(row.get("available", 0)),
            "total": int(row.get("total", 1)),
        })
    if records:
        db.library.insert_many(records)
    print(f"  [OK] Seeded {len(records)} library books")


def seed_hostel(db):
    path = SAMPLE_DIR / "hostel.xlsx"
    if not path.exists():
        print("  SKIP hostel.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    db.hostel.delete_many({})
    records = []
    for _, row in df.iterrows():
        records.append({
            "student_id": str(row.get("student_id", "")),
            "room_number": str(row.get("room_number", "")),
            "block": str(row.get("block", "")),
            "type": str(row.get("type", "")),
            "payment": str(row.get("payment", "")),
        })
    if records:
        db.hostel.insert_many(records)
    print(f"  [OK] Seeded {len(records)} hostel records")


def seed_events(db):
    path = SAMPLE_DIR / "events.xlsx"
    if not path.exists():
        print("  SKIP events.xlsx — not found")
        return
    df = pd.read_excel(path, engine="openpyxl")
    df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
    db.events.delete_many({})
    records = []
    for _, row in df.iterrows():
        raw_date = row.get("event_date")
        if isinstance(raw_date, str):
            try:
                date_obj = pd.to_datetime(raw_date).to_pydatetime()
            except Exception:
                date_obj = datetime.now(timezone.utc)
        elif hasattr(raw_date, "to_pydatetime"):
            date_obj = raw_date.to_pydatetime()
        else:
            date_obj = datetime.now(timezone.utc)
        if date_obj.tzinfo is None:
            date_obj = date_obj.replace(tzinfo=timezone.utc)

        records.append({
            "title": str(row.get("title", "")),
            "event_type": str(row.get("event_type", "")),
            "event_date": date_obj,
            "venue": str(row.get("venue", "")),
            "department": str(row.get("department", "")),
        })
    if records:
        db.events.insert_many(records)
    print(f"  [OK] Seeded {len(records)} events")


def main():
    print("=" * 60)
    print("  AI Campus Intelligence Platform — MongoDB Data Seeder")
    print("=" * 60)
    print(f"  Database: {DB_NAME}")
    print(f"  Sample data dir: {SAMPLE_DIR}")
    print()

    db = get_db()

    seed_students(db)
    seed_faculty(db)
    seed_attendance(db)
    seed_placements(db)
    seed_results(db)
    seed_timetable(db)
    seed_library(db)
    seed_hostel(db)
    seed_events(db)

    print()
    print("=" * 60)
    print("  [OK]  All sample data seeded into MongoDB!")
    print("=" * 60)


if __name__ == "__main__":
    main()
