/**
 * pages/index.js
 * Centralised export of all page components.
 * Import from here: import { DashboardPage, ChatPage } from '../pages'
 */

export { default as LoginPage }            from './LoginPage'
export { default as RegisterPage }         from './RegisterPage'
export { default as DashboardPage }        from './DashboardPage'
export { default as ChatPage }             from './ChatPage'
export { default as ChatHistoryPage }      from './ChatHistoryPage'
export { default as ProfilePage }          from './ProfilePage'
export { default as SettingsPage }         from './SettingsPage'
export { default as StudentPage }          from './StudentPage'
export { default as FacultyPage }          from './FacultyPage'
export { default as AdminPage }            from './AdminPage'
export { default as UploadPDFPage }        from './UploadPDFPage'
export { default as UploadExcelPage }      from './UploadExcelPage'
export { default as UploadCSVPage }        from './UploadCSVPage'
export { default as DocumentsPage }        from './DocumentsPage'
export { default as UsersPage }            from './UsersPage'
export { default as AnalyticsPage }        from './AnalyticsPage'
export { default as ReportsPage }          from './ReportsPage'
export { default as NotificationsPage }    from './NotificationsPage'
export { default as SystemHealthPage }     from './SystemHealthPage'
export { default as ResumeAnalyzerPage }   from './ResumeAnalyzerPage'
export { default as QuestionPaperPage }    from './QuestionPaperPage'
export { default as AttendancePage }       from './AttendancePage'
export { default as PlacementsPage }       from './PlacementsPage'
export { default as AcademicAnalyticsPage } from './AcademicAnalyticsPage'
export { default as TimetablePage }        from './TimetablePage'
export { default as CalendarPage }         from './CalendarPage'
export { default as LibraryPage }          from './LibraryPage'
export { default as HostelPage }           from './HostelPage'
export { default as EventsPage }           from './EventsPage'
export { default as NotFoundPage }         from './NotFoundPage'
